# Generated by Django 4.0 on 2022-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyfiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mf_name', models.CharField(max_length=200)),
                ('mf_units', models.FloatField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
