# Generated by Django 4.0 on 2022-01-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneyfi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyfimodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
