# Generated by Django 4.0 on 2022-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneyfi', '0002_alter_moneyfimodel_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mf_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MfDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mf_date', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='moneyfimodel',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='moneyfimodel',
            unique_together={('mf_name', 'mf_units', 'mobile')},
        ),
    ]
